name: sgl_app_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  pluto_grid: ^8.0.0
  #flutter_riverpod: ^2.5.1
  go_router: ^14.1.1
  #hooks_riverpod: ^2.5.1
  flutter_secure_storage: ^9.0.0
  brasil_fields: ^1.14.3
  dio: ^5.4.2+1
  get_it: ^7.6.8
  json_annotation: ^4.8.1
  flutter_expandable_fab: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - images/  
